### ISSUE TITLE
Add lightweight migrations to CoreData stack

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful-persistence.objc#12]
In Swift

    coordinator.addPersistentStoreWithType(NSSQLiteStoreType, 
     configuration:nil, 
     URL:self.storeURL, 
     options:NSMigratePersistentStoresAutomaticallyOption:true,
         NSInferMappingModelAutomaticallyOption:true)

https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CoreDataVersioning/Articles/vmLightweightMigration.html#//apple_ref/doc/uid/TP40004399-CH4-SW1

**Comment by neonichu** [comment]
I'm unsure about this, as it will lead to potentially missing data locally. 

Think of this scenario:

1. User has an app with model version X
2. You add a new field Y to your model, entries will have some values for Y
3. You release a new version of the app with model version X+1
4. User gets updated entries during sync, but still has the old app. Values for Y can't be stored
5. User updates their app, but since they already synced, they'll be missing the values for Y

Our recommendation for this has been wiping any local data if you change the data model and perform a fresh sync, potentially shipping a prepopulated DB to reduce the fetch time. I think <https://github.com/contentful/vault> (the Android equivalent of this library) even deletes the local DB automatically if the schema version changes.

**Comment by dmorrow** [comment]
This makes sense.  Some migration needs to happen, but the case you've laid out makes lightweight migrations impossible.

**Comment by neonichu** [comment]
It's a good point, though, we need to at least document this better.

**Comment by dmorrow** [comment]
We are forcing a clearing of the local DB prior to when a lightweight migration would occur.

In our CoreDataManager subclass:

    lazy var modelChanged:Bool = {
        guard NSFileManager.defaultManager().fileExistsAtPath(self.storeURL.path!) else { return false }
        do {
            let sourceMetadata = try NSPersistentStoreCoordinator.metadataForPersistentStoreOfType(NSSQLiteStoreType, URL:self.storeURL)
            return
                !self.managedObjectModel.isConfiguration(nil, compatibleWithStoreMetadata:sourceMetadata)
        } catch let error as NSError {
            print("model changed error \(error)")
        }
        return false
    }()

After instancing our CoreDataManager ( `var manager` ) subclass:
    
    if manager.modelChanged {
        do {
            try manager.managedObjectContext?.deleteAllObjects()
        } catch let error as NSError {
            print("erase all error \(error)")
        }
    }

**Comment by neonichu** [comment]
Thanks for sharing, I think other customers have done something similar. I will make sure to add a note on this to our documentation and will also consider making this either default or an optional, but included behaviour of `CoreDataManager` itself.
