### ISSUE TITLE
Modify Core Data error handling

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful-persistence.objc#13]
Rather than just crashing in `addPersistentStoreWithType:`, maybe show an alert to the user before crashing :smile: 

In Swift

    do {
        try coordinator.addPersistentStoreWithType(NSSQLiteStoreType,
            configuration:nil,
            URL:self.storeURL,
            options:[NSMigratePersistentStoresAutomaticallyOption:true, NSInferMappingModelAutomaticallyOption:true])
    } catch let error as NSError {
        print("Unresolved error \(error), \(error.userInfo)")
        let alert = UIAlertController(title: "Something went wrong", message: "The issue has been logged and the app will now exit", preferredStyle: UIAlertControllerStyle.Alert)
        let action = UIAlertAction(title: "Ok", style: UIAlertActionStyle.Cancel, handler: { (action) in abort() })
        alert.addAction(action)
        
        AppDelegate.delegate().window?.rootViewController?.presentViewController(alert, animated: true, completion: nil)
    }

**Comment by neonichu** [comment]
This is a good point, that part has never been changed when transitioning the code from an example to a Pod. I think the best solution is a delegate in order to not enforce any specific kind of presentation or handling or the errors. If no delegate has been provided, we'll default to the current crashing behaviour.
