### ISSUE TITLE
Please Update Documentation

### ISSUE THREAD

**Issue by AntonTheDev** [contentful/contentful-persistence.objc#23]
I got to admit, I am running into this a lot lately. Could you please update the documentation to provide a step by step walk through on how to use your seed databases? Or at least point me to a work example please.

**Comment by loudmouth** [comment]
Hi @AntonTheDev , apologies for the delayed response—I was on vacation the past few days. I agree with you that the documentation is outdated. Unfortunately, the prior maintainer didn't leave much in terms of documentation for the seed database tool. 

After doing some investigating, I found that the idea was to build the command line application locally (after cloning and setting up the contentful.objc project locally) and simply hardcode space credentials. See the [entry point for the CLI](https://github.com/contentful/contentful.objc/blob/master/Examples/SeedDatabase/CommandlineTool/main.m) and the [location in the source where you hardcode your credentials](https://github.com/contentful/contentful.objc/blob/master/Examples/SeedDatabase/CoreDataManager%2BSeedDB.m#L20). 

However, there seems to be some linking issues with the Command Line target in the project at the moment. I will need some time after my meetings this afternoon to get these issues fixed and to improve the documentation in the README here.

On a side note, I have just built a CLI for the Swift stack 2 weeks ago that does this exact thing. While it's not published on Github yet, it is fully unit-tested and working. Did you end up deciding against using the Swift stack in favor of the Objective-C analog?

**Comment by loudmouth** [comment]
@antonthedev these linking issues are a bit more severe than I originally assessed them to be. Unfortunately a fix for the bundling issue will not be available until Monday. I’ll make sure to update the documentation along with this fix. Thanks for your patience and sorry for the trouble

**Comment by loudmouth** [comment]
@AntonTheDev Travis has been having serious stability issues over the past few weeks and today has been no different. The seed database tool has been moved into it's own Xcode project so that it may build properly and my PR has been approved internally. I'm now just waiting for Travis to build contentful.objc so that it may be merged.

If you must use the tool right away, clone contentful.objc and navigate to [this directory in the relevant branch](https://github.com/contentful/contentful.objc/tree/bugfix/seed-db-cli-build/Examples/SeedDatabase/SeedDatabase-CLI). `pod install` then you can change your credentials and run the tool. The console output will inform you about the location of the sqlite files and the binary assets it downloads.

Of course, this hotfix doesn't address the original issue—documentation. It may be another day or two before all is sorted out on this front, but in the meantime, I'm hoping that patching the tooling so that is functional again a valuable step in the right direction.

Thanks again for your patience.

**Comment by loudmouth** [comment]
The fix was merged last week on contentful.objc. Now, you should be able to clone the repo and run the utility in xcode directly with your credentials attached. I have detailed some of the inner workings in the above comments, and will work on updating the documentation for this tool this week.

**Comment by loudmouth** [comment]
Closing as project is now deprecated. See [contentful-persistence.swift](https://github.com/contentful-persistence.swift)
